"""add_ai_document_generation_tables

Revision ID: 126436604a64
Revises: 0002_add_archived_job_status
Create Date: 2026-06-17 15:27:01.304894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126436604a64'
down_revision: Union[str, Sequence[str], None] = '0002_add_archived_job_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=160), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('job_description_snapshot', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cover_letter_versions_cache', 'cover_letter_versions', ['job_id', 'profile_name', 'provider', 'model'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_company_name'), 'cover_letter_versions', ['company_name'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_created_at'), 'cover_letter_versions', ['created_at'], unique=False)
    op.create_index('ix_cover_letter_versions_job_created', 'cover_letter_versions', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_job_id'), 'cover_letter_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_model'), 'cover_letter_versions', ['model'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_profile_name'), 'cover_letter_versions', ['profile_name'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_provider'), 'cover_letter_versions', ['provider'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=160), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('job_description_snapshot', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('ats_before_score', sa.Integer(), nullable=True),
    sa.Column('ats_after_score', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resume_versions_cache', 'resume_versions', ['job_id', 'profile_name', 'provider', 'model'], unique=False)
    op.create_index(op.f('ix_resume_versions_company_name'), 'resume_versions', ['company_name'], unique=False)
    op.create_index(op.f('ix_resume_versions_created_at'), 'resume_versions', ['created_at'], unique=False)
    op.create_index('ix_resume_versions_job_created', 'resume_versions', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_job_id'), 'resume_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_model'), 'resume_versions', ['model'], unique=False)
    op.create_index(op.f('ix_resume_versions_profile_name'), 'resume_versions', ['profile_name'], unique=False)
    op.create_index(op.f('ix_resume_versions_provider'), 'resume_versions', ['provider'], unique=False)
    op.create_table('ai_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=160), nullable=True),
    sa.Column('generation_type', sa.Enum('RESUME', 'COVER_LETTER', 'BOTH', name='documentkind'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'NEEDS_JD', name='aigenerationstatus'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('base_resume', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('resume_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_version_id', sa.Integer(), nullable=True),
    sa.Column('force_regenerate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_version_id'], ['cover_letter_versions.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_jobs_company_name'), 'ai_generation_jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_created_at'), 'ai_generation_jobs', ['created_at'], unique=False)
    op.create_index('ix_ai_generation_jobs_job_created', 'ai_generation_jobs', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_job_id'), 'ai_generation_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_profile_name'), 'ai_generation_jobs', ['profile_name'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_status'), 'ai_generation_jobs', ['status'], unique=False)
    op.create_index('ix_ai_generation_jobs_status_created', 'ai_generation_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_generation_jobs_status_created', table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_status'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_profile_name'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_job_id'), table_name='ai_generation_jobs')
    op.drop_index('ix_ai_generation_jobs_job_created', table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_created_at'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_company_name'), table_name='ai_generation_jobs')
    op.drop_table('ai_generation_jobs')
    op.drop_index(op.f('ix_resume_versions_provider'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_profile_name'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_model'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_job_id'), table_name='resume_versions')
    op.drop_index('ix_resume_versions_job_created', table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_created_at'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_company_name'), table_name='resume_versions')
    op.drop_index('ix_resume_versions_cache', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_cover_letter_versions_provider'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_profile_name'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_model'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_job_id'), table_name='cover_letter_versions')
    op.drop_index('ix_cover_letter_versions_job_created', table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_created_at'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_company_name'), table_name='cover_letter_versions')
    op.drop_index('ix_cover_letter_versions_cache', table_name='cover_letter_versions')
    op.drop_table('cover_letter_versions')
    # ### end Alembic commands ###
